### ISSUE TITLE
doesn't work with react-native

### ISSUE THREAD

**Issue by VictorSalton** [HolodexNet/holodex.js#3]
![image](https://user-images.githubusercontent.com/51276660/163755453-cc907325-5b6d-429f-a7ee-1dcd36a843d8.png)

I've already reinstalled the modules, cleared the cache

**Comment by VictorSalton** [comment]
The error is generic and I can't find more information about the error

**Comment by stu43005** [comment]
Released some fixes and now react-native should work :)
